#!/usr/bin/env python3
"""Measures how far the macOS/Linux port is and writes port/status/{status.json,badge.json,STATUS.md}.

Progress = 50% x share of CrypTool sources that compile + 20% if CrypTool links
         + 30% x share of passing tests (tests that do not build count as failed).
"""
import datetime
import json
import os
import re
import shlex
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
BUILD = os.environ.get('PORT_STATUS_BUILD', os.path.join(REPO, 'build-status'))
OUT = os.path.join(REPO, 'port', 'status')


def run(cmd, **kw):
    print('+', ' '.join(cmd), flush=True)
    return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True, errors='replace', **kw)


def syntax_check(entry):
    args = shlex.split(entry['command'])
    out, skip = [], False
    for a in args:
        if skip:
            skip = False
            continue
        if a in ('-o', '-MF', '-MT'):
            skip = True
            continue
        if a in ('-MD', '-c'):
            continue
        out.append(a)
    r = subprocess.run(out + ['-fsyntax-only', '-ferror-limit=0'], cwd=entry['directory'], capture_output=True,
                       text=True, errors='replace')
    return r.returncode == 0, len(re.findall(r'\berror:', r.stderr))


def main():
    configure = run(['cmake', '-S', REPO, '-B', BUILD, '-G', 'Ninja', '-DCRYPTOOL_THIRDPARTY_TESTS=ON',
                     '-DMFCWX_TESTS=ON'] + sys.argv[1:])
    if configure.returncode != 0:
        sys.stderr.write(configure.stdout[-4000:] + configure.stderr[-4000:])
        sys.exit('configure failed')

    build = run(['ninja', '-C', BUILD, '-k', '0'])
    app_dirs = ('/CrypTool/', '/ChallengeResponse/', '/libVolRen/')
    library_errors = sum(1 for line in (build.stdout + build.stderr).splitlines()
                         if 'error:' in line and not any(d in line for d in app_dirs))

    # Application sources are syntax-checked on their own so that a broken support library
    # does not hide their state.
    commands = json.load(open(os.path.join(BUILD, 'compile_commands.json')))
    units = [c for c in commands if '/CrypTool.dir/' in c.get('output', c['command'])]
    with ThreadPoolExecutor(max_workers=os.cpu_count() or 4) as pool:
        results = list(pool.map(syntax_check, units))
    compiled = sum(1 for ok, _ in results if ok)
    errors = library_errors + sum(n for _, n in results)
    linked = any(os.path.exists(os.path.join(BUILD, 'port', 'app', p))
                 for p in ('CrypTool', 'CrypTool.app/Contents/MacOS/CrypTool'))

    tests = run(['ctest', '--test-dir', BUILD, '--timeout', '300'])
    m = re.search(r'(\d+)% tests passed(?:, (\d+) tests? failed)? out of (\d+)', tests.stdout)
    total = int(m.group(3)) if m else 0
    failed = int(m.group(2) or 0) if m else 0
    passed = total - failed

    compile_share = compiled / len(units) if units else 0.0
    test_share = passed / total if total else 0.0
    progress = round(50 * compile_share + 20 * (1 if linked else 0) + 30 * test_share)

    status = {
        'progress': progress,
        'compileErrors': errors,
        'sourcesCompiled': compiled,
        'sourcesTotal': len(units),
        'linked': linked,
        'testsPassed': passed,
        'testsTotal': total,
        'updated': datetime.datetime.now(datetime.timezone.utc).strftime('%Y-%m-%d %H:%M UTC'),
    }
    colour = 'red' if progress < 34 else 'orange' if progress < 67 else 'yellow' if progress < 100 else 'brightgreen'
    os.makedirs(OUT, exist_ok=True)
    json.dump(status, open(os.path.join(OUT, 'status.json'), 'w'), indent=2)
    json.dump({'schemaVersion': 1, 'label': 'macOS/Linux port', 'message': f'{progress}%', 'color': colour},
              open(os.path.join(OUT, 'badge.json'), 'w'))
    with open(os.path.join(OUT, 'STATUS.md'), 'w') as f:
        f.write(f"""# Port status (generated by port/tools/port_status.py)

| Metric | Value |
|---|---|
| Progress | **{progress}%** |
| Compile errors | {errors} |
| CrypTool sources compiling | {compiled} / {len(units)} |
| CrypTool links | {'yes' if linked else 'no'} |
| Tests passing | {passed} / {total} |
| Updated | {status['updated']} |

Progress = 50% x sources compiling + 20% if the app links + 30% x tests passing.
""")
    print(json.dumps(status, indent=2))


if __name__ == '__main__':
    main()
